name: Build and deploy ASP.Net Core app to Azure Web Apps

on:
  push:
    # Every push (to any branch) will trigger the dev deployment.
    branches:
      - '*'  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the target environment: dev or prod'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-dev:
    # Run automatically on push, or when manually triggered with environment=dev.
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure (Dev)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_246417F9F017468A846943D678968AFC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_652BCCB883684991A761C5D60AA3D93A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B67CBE9406E14B5AAD7D5DFF0E42C096 }}

      - name: Deploy to Azure Web App (Dev)
        id: deploy-to-webapp-dev
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NLSequel-dev'
          slot-name: 'Production'
          package: .

  deploy-prod:
    # This job only runs when you manually trigger the workflow with environment=prod.
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure (Prod)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_PROD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_PROD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_PROD }}

      - name: Deploy to Azure Web App (Prod)
        id: deploy-to-webapp-prod
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NLSequel-prod'
          slot-name: 'Production'
          package: .
